site_name: Backend Learning
site_url: "https://rrrexyz.github.io/BackendLearning/"
theme: minty
nav:
  - Home: index.md
  - Git:
    - Git安装: git.md
    - Git入门: git2.md
  - 后端开发: 
    - Python配置: python.md
  - 懂的都懂:
    - 科学上网: ladder.md